### ISSUE TITLE
Clarifying input and output

### ISSUE THREAD

**Issue by amisios** [rajewsky-lab/PyMAF#1]
Hello,
Some people in the Rajewsky lab suggested to me to use this software to work with multiple alignments.
I am looking at a specific region of the mouse genome.

Currently it is not clear to me what the input bed file needs to be, And what is exactly the output is supposed to be.

Thirdly, when I try to use PyMAF with a minimal input bed file (chrX    58430000    58444000), I get the following error

Traceback (most recent call last):
  File "../PyMAF/pymaf", line 230, in <module>
    for aln,name in handler(MAF_track, src, system=options.reference, segments=options.segments.split(','), flank=options.flank, sort_chrom=options.sort_chrom):
  File "../PyMAF/pymaf", line 145, in process_bed6
    for bed in records:
  File "/home/amisios/bin/byo/io/bed.py", line 6, in bed_importer
    for rec in NamedTupleImporter(src,descr=bed6_default,parse_comments=True,default_cast='str',keep_line=True,**kwargs):
  File "/home/amisios/bin/byo/io/lazytables.py", line 193, in __iter__
    data = [c(v) for c,v in itertools.izip_longest(casts,vals,fillvalue=str)][:len(casts)]
TypeError: int() argument must be a string or a number, not 'type'

Thanks you.

**Comment by marvin-jens** [comment]
Hi Amisios,

PyMAF is under development and not officially released. However, I am happy if 
it can be helpful to you already. Just understand that I don't have a lot of 
time on my hand for trouble shooting your specific project.
The input needs to be BED6, so name and score are missing in your input. Also, 
please make sure that columns are delimited by tab.
The output will be a multiple species FASTA file. If you use --muscle <n> with 
n > 0 (16 is good), it will be an actual multiple-species alignment, with gaps 
etc.
But be aware that you first need to obtain all the genomes (2bit files) and 
convert all the MAF files to HDF5 format for fast lookup. There are commandline 
scripts in PyMAF to do that, but it will quite some take space and time. For 
what you are trying to do, it may perhaps be easier to use the ensembl Compara 
suite. https://academic.oup.com/database/article-lookup/doi/10.1093/database/
bav096

Best regards,
  -Marvin

**Comment by mschilli87** [comment]
Hey Marvin,

Thx for the fast response.

Regarding the HDF5 genomes:
I just wanted to add that Aristotelis happens to have access to BIO3. ;)

Cheers,
Marcel

**Comment by marvin-jens** [comment]
Hey, sure.
I see. It's HDF5 MAF files, though ;) I did a bit of work on this here in 
Boston. Could be (actually quite certain) that the BIO3 stuff is out of date.

Aristotelis did not mention how exactly he was associated with the lab. So I 
did not know he has that access. Andrei successfully used a previous version 
of my code, so he would probably be a useful person for him to talk to.

Best,
  -Marvin
